// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class MetadataCreated extends ethereum.Event {
  get params(): MetadataCreated__Params {
    return new MetadataCreated__Params(this);
  }
}

export class MetadataCreated__Params {
  _event: MetadataCreated;

  constructor(event: MetadataCreated) {
    this._event = event;
  }

  get dataToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get createdBy(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get flags(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }

  get data(): Bytes {
    return this._event.parameters[3].value.toBytes();
  }
}

export class MetadataUpdated extends ethereum.Event {
  get params(): MetadataUpdated__Params {
    return new MetadataUpdated__Params(this);
  }
}

export class MetadataUpdated__Params {
  _event: MetadataUpdated;

  constructor(event: MetadataUpdated) {
    this._event = event;
  }

  get dataToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get updatedBy(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get flags(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }

  get data(): Bytes {
    return this._event.parameters[3].value.toBytes();
  }
}

export class Metadata extends ethereum.SmartContract {
  static bind(address: Address): Metadata {
    return new Metadata("Metadata", address);
  }
}

export class CreateCall extends ethereum.Call {
  get inputs(): CreateCall__Inputs {
    return new CreateCall__Inputs(this);
  }

  get outputs(): CreateCall__Outputs {
    return new CreateCall__Outputs(this);
  }
}

export class CreateCall__Inputs {
  _call: CreateCall;

  constructor(call: CreateCall) {
    this._call = call;
  }

  get dataToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get flags(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }

  get data(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class CreateCall__Outputs {
  _call: CreateCall;

  constructor(call: CreateCall) {
    this._call = call;
  }
}

export class UpdateCall extends ethereum.Call {
  get inputs(): UpdateCall__Inputs {
    return new UpdateCall__Inputs(this);
  }

  get outputs(): UpdateCall__Outputs {
    return new UpdateCall__Outputs(this);
  }
}

export class UpdateCall__Inputs {
  _call: UpdateCall;

  constructor(call: UpdateCall) {
    this._call = call;
  }

  get dataToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get flags(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }

  get data(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class UpdateCall__Outputs {
  _call: UpdateCall;

  constructor(call: UpdateCall) {
    this._call = call;
  }
}
